// Site-wide constants
export const SITE_TITLE = 'United Tattoo';
export const SITE_DESCRIPTION = 'Tattoo studio in Fountain, CO';
export const ADDRESS_LINE_1 = '5160 Fontaine Blvd';
export const ADDRESS_LINE_2 = 'Fountain, CO 80817';
export const LOCATION = `${ADDRESS_LINE_1}, ${ADDRESS_LINE_2}`;
export const PHONE_NUMBER = '+1 719 698 9004';
export const EMAIL = 'ink@unitedtattoos.com';
export const INSTAGRAM = 'https://www.instagram.com/unitedtattoosco/';
export const YOUTUBE = 'https://www.youtube.com/@UnitedTattoo';
export const YELP = 'https://www.yelp.com/biz/united-tattoo-fountain';
export const INKROSTER = 'https://inkroster.com/studios/united-tattoo/';
export const NEWSINSIDERPOST_ARTICLE = 'https://newsinsiderpost.com/why-united-tattoo-studio-in-fountain-is-worth-the-drive-from-colorado-springs/';
export const TATTOO_CONVENTIONS_ARTICLE = 'https://journalposttoday.com/famous-tattoo-conventions-around-the-world/';
export const URL = 'https://united-tattoos.com';
export const ADDRESS_LOCALITY = 'Fountain';
export const ADDRESS_REGION = 'CO';
export const POSTAL_CODE = '80817';
export const COUNTRY_CODE = 'US';
export const GEO_LATITUDE = 38.7367359;
export const GEO_LONGITUDE = -104.7320189;
export const GOOGLE_MAPS_URL = 'https://www.google.com/maps/dir//5160+Fontaine+Blvd,+Fountain,+CO+80817/@38.736707,-104.8144199,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x87134127d88898d3:0xf6ed49a9b9f5ce7e!2m2!1d-104.7320189!2d38.7367359';
